language: julia
os:
  - linux
  - osx
  - windows
arch:
  - amd64
  - arm64
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
    email: false
branches:
    only:
        - master

after_success:
    - julia -e 'cd(Pkg.dir("GZip")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
